>>> print(divisor)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'divisor' is not defined
Para pensar ğŸ¤”: Â¿QuÃ© nos dice el mensaje de excepciÃ³n? Â¿QuÃ© es la excepciÃ³n de nombre?
nos dice que no hay ninguna variable llamada divisor. No sabe que imprimir porque no estÃ¡ definido.
NameError â†’ no se encuentra un nombre local o global

>>> 0 + "2"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Para pensar ğŸ¤”: Â¿QuÃ© nos dice el Ãºltimo mensaje de excepciÃ³n? Â¿QuÃ© es la excepciÃ³n de tipo?
Nos dice que no se puede sumar un int. y un string
TypeError â†’ Se genera cuando una operaciÃ³n o funciÃ³n se aplica a un objeto de tipo inapropiado. 


